version: '3.7'

services:
  terraform:
    image: hashicorp/terraform:1.2.8
    volumes:
      - ./tf:/tf
    working_dir: /tf
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
