name: CD

on: 
  push:
    branches: 
      - dev
      - uat
      - prd

jobs:
  format:
    uses: ./.github/workflows/job_formatting.yml
  lint:
    uses: ./.github/workflows/job_linting.yml
  test:
    uses: ./.github/workflows/job_testing.yml
  build_and_push:
    uses: ./.github/workflows/job_build_push.yml
    secrets: inherit
    needs: [ format, lint, test ]
