name: Continuous Integration
on: [pull_request]
jobs:
  call-another-job:
    uses: ./.github/workflows/foo.yml
  # uses: ./.github/workflows/linting.yml
  # linting: Joris1Jansen/simplebank/.github/workflows/linting.yml
