name: Lint Golang && Terraform
on:
  workflow_call:
jobs:
  lint_golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  lint_terraform_envs:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize Terraform (dev)
        run: make tf-init-nb env=dev

      - name: Lint Terraform (dev) 
        run: make tf-fmt-check env=dev 

      - name: Initialize Terraform (uat)
        run: make tf-init-nb env=uat

      - name: Lint Terraform (dev) 
        run: make tf-fmt-check env=uat 

      - name: Initialize Terraform (prd)
        run: make tf-init-nb env=prd

      - name: Lint Terraform (prd) 
        run: make tf-fmt-check env=prd 
  # lint_terraform_dev:
  #   name: Lint Terraform dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Lint Terraform
  #       run: |
  #         cd ./.deploy/dev/tf
  #         terraform init -backend=false
  #         terraform fmt -check
  #
  # lint_terraform_uat:
  #   name: Lint Terraform uat
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Lint Terraform
  #       run: |
  #         cd ./.deploy/uat/tf
  #         terraform init -backend=false
  #         terraform fmt -check
  #
  # lint_terraform_prd:
  #   name: Lint Terraform uat
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Lint Terraform
  #       run: |
  #         cd ./.deploy/prd/tf
  #         terraform init -backend=false
  #         terraform fmt -check
