name: Lint Golang && Terraform
on:
  workflow_call:
jobs:
  lint_golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Glang 
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  # lint_terraform:
  #   name: Lint Terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Initialize Terraform (dev)
  #       run: |
  #         cd ./.deploy/dev/tf
  #         terraform init -backend=false
  #
  #     - name: Lint Terraform (dev) 
  #       run: |
  #         terraform validate 
  #         cd ../..

      # - name: Initialize Terraform (uat)
      #   run: |
      #     cd ./uat/tf
      #     terraform init -backend=false
      #
      # - name: Lint Terraform (uat) 
      #   run: |
      #     terraform validate 
      #     cd ../..
      #
      # - name: Initialize Terraform (prd)
      #   run: |
      #     cd ./prd/tf
      #     terraform init -backend=false
      #
      # - name: Lint Terraform (prd) 
      #   run: |
      #     terraform validate 
      #     cd ../..
