name: Format Golang && Terraform
on:
  workflow_call:
jobs:
  format_golang:
    name: Format Golang
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Format Glang 
        run: ./scripts/go_fmt.sh

  format_terraform:
    name: Format Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Initialize Terraform (dev)
        run: terraform -chdir=.deploy/dev/tf init -backend=false 
  
      - name: Format Terraform (dev) 
        run: terraform -chdir=.deploy/dev/tf fmt -check
  
      - name: Initialize Terraform (uat)
        run: terraform -chdir=.deploy/uat/tf init -backend=false 
  
      - name: Format Terraform (uat) 
        run: terraform -chdir=.deploy/uat/tf fmt -check
      
      - name: Initialize Terraform (prd)
        run: terraform -chdir=.deploy/prd/tf init -backend=false 
  
      - name: Format Terraform (prd) 
        run: terraform -chdir=.deploy/prd/tf fmt -check
