name: Lint Golang && Terraform
on:
  workflow_call:
jobs:
  lint_golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Glang 
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  lint_terraform:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Initialize Terraform (dev)
        run: terraform -chdir=.deploy/dev/tf init -backend=false 
  
      - name: Format Terraform (dev) 
        run: terraform -chdir=.deploy/dev/tf validate 

      - name: Initialize Terraform (uat)
        run: terraform -chdir=.deploy/uat/tf init -backend=false 
  
      - name: Format Terraform (uat) 
        run: terraform -chdir=.deploy/uat/tf validate 

      - name: Initialize Terraform (prd)
        run: terraform -chdir=.deploy/prd/tf init -backend=false 
  
      - name: Format Terraform (prd) 
        run: terraform -chdir=.deploy/prd/tf validate 
