name: Format Golang && Terraform
on:
  workflow_call:
jobs:
  format_golang:
    name: Format Golang
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Format Glang 
        run: gofmt -d .

  format_terraform:
    name: Format Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize Terraform (dev)
        run: make tf-init-nb env=dev

      - name: Format Terraform (dev) 
        run: make tf-fmt-check env=dev 

      - name: Initialize Terraform (uat)
        run: make tf-init-nb env=uat

      - name: Format Terraform (uat) 
        run: make tf-fmt-check env=uat 

      - name: Initialize Terraform (prd)
        run: make tf-init-nb env=prd

      - name: Format Terraform (prd) 
        run: make tf-fmt-check env=prd 
